In [1]:
import numpy as np

# 逻辑运算

In [2]:
# 随机生成10位学生5门功课成绩，分数范围40-100
score = np.random.randint(40, 100, (10, 5))

In [3]:
score

array([[90, 51, 66, 45, 57],
       [77, 96, 81, 77, 41],
       [57, 53, 47, 67, 57],
       [40, 62, 83, 47, 66],
       [45, 88, 49, 72, 81],
       [85, 95, 68, 40, 81],
       [53, 72, 55, 73, 63],
       [69, 43, 52, 74, 96],
       [84, 95, 68, 69, 73],
       [75, 60, 99, 62, 83]])

In [4]:
# 最后4位学生的成绩
test_score = score[6:, 0:5]

In [5]:
test_score

array([[53, 72, 55, 73, 63],
       [69, 43, 52, 74, 96],
       [84, 95, 68, 69, 73],
       [75, 60, 99, 62, 83]])

In [6]:
# 逻辑判断, 如果成绩大于60就标记为True 否则为False
test_score > 60

array([[False,  True, False,  True,  True],
       [ True, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [11]:
# BOOL赋值, 将满足条件的设置为指定的值-布尔索引
test_score[test_score > 60] = 1

In [13]:
test_score

array([[53,  1, 55,  1,  1],
       [ 1, 43, 52,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 1, 60,  1,  1,  1]])

# 通用判断函数

In [14]:
# np.all() 所有元素都满足要求才返回True
np.all(score[0:2, :] > 60)

False

In [15]:
score

array([[90, 51, 66, 45, 57],
       [77, 96, 81, 77, 41],
       [57, 53, 47, 67, 57],
       [40, 62, 83, 47, 66],
       [45, 88, 49, 72, 81],
       [85, 95, 68, 40, 81],
       [53,  1, 55,  1,  1],
       [ 1, 43, 52,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 1, 60,  1,  1,  1]])

In [16]:
# np.any() 任意元素满足要求就返回True
np.any(score[0:2, :] > 90)

True

# 三元运算符

In [18]:
temp = score[:4, :4]

In [19]:
temp

array([[90, 51, 66, 45],
       [77, 96, 81, 77],
       [57, 53, 47, 67],
       [40, 62, 83, 47]])

In [20]:
np.where(temp > 60, 1, 0)

array([[1, 0, 1, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [0, 1, 1, 0]])

In [21]:
temp

array([[90, 51, 66, 45],
       [77, 96, 81, 77],
       [57, 53, 47, 67],
       [40, 62, 83, 47]])

In [22]:
np.logical_and(temp > 60, temp < 90)

array([[False, False,  True, False],
       [ True, False,  True,  True],
       [False, False, False,  True],
       [False,  True,  True, False]])

In [23]:
np.where(np.logical_and(temp > 60, temp < 90), 1, 0)

array([[0, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 0, 0, 1],
       [0, 1, 1, 0]])

In [27]:
np.where(np.logical_or(temp < 60, temp > 90), 1, 0)

array([[0, 1, 0, 1],
       [0, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 0, 0, 1]])

# 统计运算

In [29]:
temp = score[:4, :]

In [30]:
temp

array([[90, 51, 66, 45, 57],
       [77, 96, 81, 77, 41],
       [57, 53, 47, 67, 57],
       [40, 62, 83, 47, 66]])

In [31]:
np.max(temp)

96

In [37]:
# 按列
np.max(temp, axis=0)

array([90, 96, 83, 77, 66])

In [42]:
# 按行
np.max(temp, axis=1)

array([90, 96, 67, 83])

In [43]:
# 中位数
np.median(temp, axis=1)

array([57., 77., 57., 62.])

In [39]:
# 平均数
np.mean(temp, axis=0)

array([66.  , 65.5 , 69.25, 59.  , 55.25])

In [40]:
# 标准差
np.std(temp, axis=0)

array([19.06567596, 18.09005252, 14.42870403, 13.49073756,  9.01041065])

In [41]:
# 方差
np.var(temp, axis=0)

array([363.5   , 327.25  , 208.1875, 182.    ,  81.1875])

In [34]:
np.argmax(temp)

6

In [35]:
np.argmax(temp, axis=0)

array([0, 1, 3, 1, 3])

In [36]:
np.argmax(temp, axis=1)

array([0, 1, 3, 2])