## numpy

In [1]:
import numpy as np

In [2]:
# 创建ndarray
store = np.array(
    [[80, 89, 86, 67, 79],
    [78, 97, 89, 67, 81],
    [90, 94, 78, 67, 74],
    [91, 91, 90, 67, 69],
    [76, 87, 75, 67, 86],
    [70, 79, 84, 67, 84],
    [94, 92, 93, 67, 64],
    [86, 85, 83, 67, 80]]
)

In [3]:
store

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

### ndarray和原生python list类型效率对比

In [4]:
import random
import time

In [5]:
a = [random.random() for i in range(100)]

In [6]:
# 通过%time魔法方法, 查看当前行的代码运行一次所花费的时间
%time sum1 = sum(a)

CPU times: user 8 µs, sys: 1 µs, total: 9 µs
Wall time: 12.9 µs


In [7]:
b = np.array(a)

In [8]:
%time sum2 = np.sum(b)

CPU times: user 40 µs, sys: 6 µs, total: 46 µs
Wall time: 48.9 µs


## ndarray使用

### 数组的属性

In [9]:
store

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

In [10]:
# 描述数组维度的元祖
store.shape

(8, 5)

In [11]:
# 数组的维数
store.ndim

2

In [12]:
# 数组中所有单个一维元素的数量
store.size

40

In [13]:
# 单个数组元素的长度（字节）
store.itemsize

8

In [14]:
# 数组元素的类型
store.dtype

dtype('int64')

### 数组的形状

In [15]:
a1 = np.array([[1,2,3],[4,5,6]])
a1.shape

(2, 3)

In [16]:
a2 = np.array([1,2,3])
a2.shape

(3,)

In [17]:
# 三维数组
# share返回的元祖数字为由外到内每个维度数组的元素个数
a3 = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
a3.shape

(2, 2, 3)

### 数组的类型

In [18]:
store.dtype

dtype('int64')

In [19]:
type(store.dtype)

numpy.dtype

In [23]:
s1 = np.array(['a', 'b', 'c'])
s1

array(['a', 'b', 'c'], dtype='<U1')

In [25]:
# dtype='|S5', 5代表数组中单个元素的最大长度
s2 = np.array(['abcde', 'b', 'c'], dtype=np.string_)
s2

array([b'abcde', b'b', b'c'], dtype='|S5')

In [26]:
# 注意：若不指定，整数默认int64，小数默认float64
f1 = np.array([1,2,3])
f1

array([1, 2, 3])

In [27]:
# 设置np.float32会自动给整数元素添加小数点
f2 = np.array([1,2,3], dtype=np.float32)
f2

array([1., 2., 3.], dtype=float32)