# 数组间的运算

## 数组与数的运算

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# 未修改原数组，生成新数组
a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [5]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [6]:
b = [1, 2, 3]

In [7]:
# b + 1 # 报错

In [8]:
# python中list*数字是复制元素
b * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

## 数组与数组的运算

In [9]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [10]:
arr1 + arr2 # 报错

ValueError: operands could not be broadcast together with shapes (2,6) (2,4) 

## 广播机制

数组在进行矢量化运算时，要求数组的形状是相等的。当形状不相等的数组执行算术运算的时候，就会出现广播机制，该机制会对数组进行扩展，使数组的shape属性值一样，这样，就可以进行矢量化运算了。

满足以下任意一种情况，都可能发生广播：

- 如果两个数组的末尾维度（trailing dimension)的长度相符；
- 参与计算的某个维度长度为 1，广播会在缺失和（或）长度为 1 的维度上进行

In [ ]:
a = np.array([[1, 1], [2, 1]])

In [ ]:
b = np.array([[1, 1, 1], [2, 2, 2]])

In [ ]:
b

In [ ]:
a + b

In [ ]:
c = [[1], [2]]

In [ ]:
c

In [ ]:
b + c

In [12]:
x1 = np.array([1, 2, 3])

In [13]:
x2 = np.array([1, 1])

In [17]:
# x1 + x2 # ValueError: operands could not be broadcast together with shapes (3,) (2,)