# 矩阵运算

np.matmul和np.dot的区别:

二者都是矩阵乘法。 np.matmul中禁止矩阵与标量的乘法。 在矢量乘矢量的內积运算中，np.matmul与np.dot没有区别。

## np.dot

In [2]:
import numpy as np

In [3]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

In [4]:
a

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

In [5]:
b = np.array([[0.7], [0.3]])

In [12]:
b

array([[0.7],
       [0.3]])

In [13]:
np.dot(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [14]:
c = 2

In [15]:
np.dot(a, c)

array([[160, 172],
       [164, 160],
       [170, 156],
       [180, 180],
       [172, 164],
       [164, 180],
       [156, 160],
       [184, 188]])

## np.matmul()

In [9]:
np.matmul(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [11]:
# np.matmul(a, c)
# ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)